# Generated by Django 5.1 on 2024-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='agility_level',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='overall_level',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='stamina_level',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='strength_level',
        ),
        migrations.AddField(
            model_name='userstats',
            name='category1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='category2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='category3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
