# Generated by Django 5.1 on 2024-09-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0003_userstatsagility_userstatsstamina_userstatsstrength_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatsagility',
            old_name='balance',
            new_name='kick_height',
        ),
    ]
