# Generated by Django 5.1 on 2024-09-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0004_rename_balance_userstatsagility_kick_height'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatsstamina',
            old_name='breath_control',
            new_name='burpees',
        ),
        migrations.RenameField(
            model_name='userstatsstamina',
            old_name='endurance',
            new_name='plank',
        ),
        migrations.RenameField(
            model_name='userstatsstamina',
            old_name='recovery',
            new_name='run',
        ),
    ]
