# Generated by Django 5.1 on 2024-09-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0007_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchpress_kg', models.IntegerField()),
                ('deadlift_kg', models.IntegerField()),
                ('squats_kg', models.IntegerField()),
                ('run_100m_seconds', models.IntegerField()),
                ('vertical_jump_height_cm', models.IntegerField()),
                ('kick_height_cm', models.IntegerField()),
                ('run_5km_minutes', models.IntegerField()),
                ('burpees_60sec', models.IntegerField()),
                ('plank_minutes', models.IntegerField()),
                ('benchpress_media', models.FileField(blank=True, null=True, upload_to='media/benchpress/')),
                ('deadlift_media', models.FileField(blank=True, null=True, upload_to='media/deadlift/')),
                ('squats_media', models.FileField(blank=True, null=True, upload_to='media/squats/')),
                ('run_100m_media', models.FileField(blank=True, null=True, upload_to='media/run_100m/')),
                ('vertical_jump_media', models.FileField(blank=True, null=True, upload_to='media/vertical_jump/')),
                ('kick_media', models.FileField(blank=True, null=True, upload_to='media/kick/')),
                ('run_5km_media', models.FileField(blank=True, null=True, upload_to='media/run_5km/')),
                ('burpees_media', models.FileField(blank=True, null=True, upload_to='media/burpees/')),
                ('plank_media', models.FileField(blank=True, null=True, upload_to='media/plank/')),
            ],
        ),
    ]
