# Generated by Django 5.1 on 2024-09-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LevelUp', '0008_mediasubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediasubmission',
            name='benchpress_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='burpees_60sec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='deadlift_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='kick_height_cm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='plank_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='run_100m_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='run_5km_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='squats_kg',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediasubmission',
            name='vertical_jump_height_cm',
            field=models.IntegerField(default=0),
        ),
    ]
